sonar.projectKey=jramosalc_ucv-ate-si-laboratorio11
sonar.organization=jramosalc
sonar.projectName=ucv-ate-si-laboratorio11
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8